Localstorage implementation
muhammaduzairrazaq/Portfolio-finish-mobile-version pull request #11
Opened 2023-08-07 19:21 UTC by muhammaduzairrazaq

**Requirements fulfilled:**

- You should implement the following interactions:
- When the user changes the content of any input field, the data is saved to the local storage.
- When the user loads the page, if there is any data in the local storage the input fields are pre-filled with this data.
- You should use the following data model:
- You must create a single JavaScript object with all the data from the entire form and save it in local storage. Do not create one local storage entry per input field.

2023-09-20 07:17 UTC, emhamza requested changes
@muhammaduzairrazaq  Great Job so far
But I am afraid your Pull request needs some required changes. Please read the message below for more information or ask me on WhatsApp:

![Uploading so-close-reaching-out.gif…]()

2023-09-20 07:17 UTC, emhamza commented on script.js
> +}
@muhammaduzairrazaq I can see you adding a function for local storage but I cannot see where are you calling this function and I also cannot see the data in the browser. Please revisit this pull request and make sure the data will be saved in the browser: 
YOUR STORAGE:
![uzair](https://github.com/muhammaduzairrazaq/portfolio/assets/122353030/626b5d7d-adac-4c04-8801-946d80022cfc)

How
![hamza](https://github.com/muhammaduzairrazaq/portfolio/assets/122353030/e354edb4-e6e4-409b-ac3c-225ff2d4cb48)
 it should look like:

2023-09-20 07:34 UTC, muhammaduzairrazaq commented
Thanks for reviewing! Issue resolved :sunglasses: 
![image](https://github.com/muhammaduzairrazaq/portfolio/assets/138608690/18342c81-8181-4b01-8db7-31c34bc9ce9e)

2023-10-02 08:39 UTC, emhamza approved these changes
Hello @muhammaduzairrazaq 
Congratulations 🥳 
Your project has approved, there is nothing to say other than it is time to move on to your next project. Best of luck and happy coding 👍

2023-10-02 14:25 UTC, merged